name: Monorepo CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js using .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install all workspace dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

  build-and-test-client:
    name: Build and Test Client
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js using .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install client dependencies
        run: npm ci

      - name: Build client application
        working-directory: ./client
        run: npm run build --if-present

      - name: Run client tests
        working-directory: ./client
        run: npm test

  build-and-test-server:
    name: Build and Test Server
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js using .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: package-lock.json # 依賴根目錄的 package-lock.json

      - name: Install server dependencies
        run: npm ci

      - name: Build server application
        working-directory: ./server
        run: npm run build --if-present

      - name: Run server tests
        working-directory: ./server
        run: npm test
