name: Monorepo CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # 1. 統一的依賴安裝 Job (這一步將會負責所有 Workspace 的依賴安裝)
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm" 

      - name: Clean npm cache (Optional but recommended for stubborn issues)
        run: npm cache clean --force
      - name: Install Monorepo dependencies
        run: npm install

  # 2. Lint Job
  lint:
    runs-on: ubuntu-latest
    needs: install-dependencies 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm" 

      - name: Install Monorepo dependencies (from cache if possible)
        run: npm install

      - name: Run Monorepo Lint
        run: npm run lint

  # 3. Client Build & Test Job
  client-build-test:
    runs-on: ubuntu-latest
    needs: install-dependencies 
    # defaults: # 注意：working-directory 設置在步驟中更靈活
    #   run:
    #     working-directory: ./client
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install Monorepo dependencies (from cache if possible)
        run: npm install --prefix ../

      - name: Build client application
        run: npm run build --if-present
        working-directory: ./client

      - name: Run client tests
        run: npm test
        working-directory: ./client 

  # 4. Server Build & Test Job
  server-build-test:
    runs-on: ubuntu-latest
    needs: install-dependencies 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install Monorepo dependencies (from cache if possible)
        run: npm install --prefix ../

      - name: Build server application
        run: npm run build --if-present
        working-directory: ./server

      - name: Run server tests
        run: npm test
        working-directory: ./server
