name: Monorepo CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js with cache
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install Monorepo dependencies
        run: npm install

      - name: Run Monorepo Lint
        run: npm run lint

      - name: Build client application
        run: npm run build --if-present
        working-directory: ./client

      - name: Run client tests
        run: npm test
        working-directory: ./client

      - name: Build server application
        run: npm run build --if-present
        working-directory: ./server

      - name: Run server tests
        run: npm test
        working-directory: ./server
